### PR TITLE
Update pb source

### PR DESCRIPTION
**Pull request by adriangb**
Adds type stubs

This is what it looks like in my IDE now if I hover over `pomerium.Client.ActivityLogService`:
Screen Shot 2021-09-22 at 11 12 33 AM

I also ran mypy and I get no errors 😄

### CODE REVIEW

**Comment by adriangb** [comment]
@travisgroth I copied the wrong dir the first time, this latest commit is correct. It only adds `.pyi` files, all of the `.py` generated files are unchanged

**Comment by travisgroth** [comment]
Hi @adriangb would you mind making this PR to https://github.com/pomerium/enterprise-client/tree/master/python/pb and update the `Makefile` with the right flags?  This repo is primarily copied from the upstream `enterprise-client` repo.

**Comment by adriangb** [comment]
I thought I did that already in https://github.com/pomerium/enterprise-client/commit/5d9b8fccceac639a81d654d33661066f6b6a3e93#diff-1c15cbed957195f901865f677040afec9089d5f9576d18954fb08510e94e734e and this PR is just copying over those files?

**Comment by travisgroth** [comment]
Oh that should have been automatic then.  Will look.

**Comment by travisgroth** [comment]
@adriangb I think they're already copied https://github.com/pomerium/enterprise-client-python/blob/master/src/pomerium/pb/activity_log_pb2.pyi.  Does that look right?  If so, we can just close this 😄

**Comment by adriangb** [comment]
Yep looks good!

**Pull request closed without merging**
